name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
        env:
          GATSBY_STRAPI_URL: ${{ secrets.GATSBY_STRAPI_URL}}
          GATSBY_FORMSPREE_ID: ${{ secrets.GATSBY_FORMSPREE_ID}}
          GATSBY_RECAPTCHA_SITE_KEY: ${{ secrets.GATSBY_RECAPTCHA_SITE_KEY}}
          GATSBY_RECAPTCHA_SECRET_KEY: ${{ secrets.GATSBY_RECAPTCHA_SECRET_KEY}}
          